image: node:latest

before_script:
 - npm prune
 - npm install
 - npm install node-sass --only=dev
 - npm install -g firebase-tools

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: "$CI_BUILD_REPO"


deploy_to_firebase:
 stage: deploy
 only:
  - master
 script:
  - npm run build
  - firebase deploy --token "1/nA72ca80vcf7kSrW9Rcby9CsZaRA1XXCHRsCxme1cCE"